import React, { useState } from 'react';
import { Sparkles, Brain, Shield, Clock, TrendingUp, Search } from 'lucide-react';
import api from '../services/api';

const AIInsights = () => {
  const [search, setSearch] = useState('bitcoin');
  const [insight, setInsight] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchInsight = async () => {
    setLoading(true);
    setError(null);
    try {
      const assetRes = await api.get(`/assets/crypto/${search}`);
      const assetData = JSON.stringify(assetRes.data);
      const brainRes = await api.post('/ai/insight', assetData);
      
      // Basic parsing of the AI result
      const fullText = brainRes.data;
      setInsight({
        trend: fullText.includes('Bullish') ? 'Bullish' : (fullText.includes('Bearish') ? 'Bearish' : 'Neutral'),
        risk: fullText.includes('High') ? 'High' : (fullText.includes('Low') ? 'Low' : 'Moderate'),
        explanation: fullText,
        outlook: '7-14 Days'
      });
    } catch (err) {
      setError('AI Insight Engine currently unavailable. Please check your API keys.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-10 pb-12 animate-in fade-in duration-700">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
        <div>
          <h2 className="text-4xl font-bold flex items-center gap-4 tracking-tight">
            <div className="p-2.5 bg-blue-500/10 rounded-2xl">
              <Sparkles className="text-blue-400 w-8 h-8" />
            </div>
            AI Insight Engine
          </h2>
          <p className="text-muted-foreground mt-3 text-lg">Deep analysis powered by Mistral 7B LLM.</p>
        </div>
        
        <div className="flex flex-col sm:flex-row gap-4 w-full md:w-auto">
          <div className="relative group w-full sm:w-auto">
            <input
              type="text"
              placeholder="Asset Symbol (BTC)..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && fetchInsight()}
              className="bg-white/5 border border-white/10 px-12 py-4 rounded-2xl w-full sm:w-72 focus:outline-none focus:border-blue-500/50 focus:ring-4 focus:ring-blue-500/10 transition-all text-white placeholder:text-muted-foreground"
            />
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground group-focus-within:text-blue-400 transition-colors" />
          </div>
          <button 
            onClick={fetchInsight}
            disabled={loading}
            className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 px-8 py-4 rounded-2xl font-bold flex items-center justify-center gap-3 transition-all disabled:opacity-50 shadow-lg shadow-blue-500/25 group w-full sm:w-auto whitespace-nowrap"
          >
            {loading ? 'Analyzing...' : <>Analyze Now <Sparkles className="w-5 h-5 group-hover:rotate-12 transition-transform" /></>}
          </button>
        </div>
      </div>

      {!insight && !loading && !error && (
        <div className="flex flex-col items-center justify-center p-24 premium-card text-center border-dashed border-2 border-white/10 bg-transparent">
          <div className="w-24 h-24 bg-blue-500/10 rounded-[2rem] flex items-center justify-center mb-8 relative glow-blue">
            <div className="absolute inset-0 bg-blue-400/20 blur-xl rounded-full"></div>
            <Brain className="w-12 h-12 text-blue-400 relative z-10" />
          </div>
          <h3 className="text-3xl font-bold tracking-tight">Ready for Analysis</h3>
          <p className="text-muted-foreground mt-4 max-w-lg mx-auto text-lg leading-relaxed">
            Input an asset symbol above to get real-time trends, risk levels, and outlooks generated by AI.
          </p>
        </div>
      )}

      {loading && (
        <div className="flex flex-col items-center justify-center p-32 premium-card">
          <div className="relative w-24 h-24 mb-8">
            <div className="absolute inset-0 border-t-4 border-blue-500 rounded-full animate-spin"></div>
            <Brain className="w-10 h-10 text-blue-400 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-pulse" />
          </div>
          <p className="text-muted-foreground font-medium text-lg animate-pulse tracking-wide">Scanning market data and processing insights...</p>
        </div>
      )}

      {error && (
        <div className="p-10 premium-card border-red-500/30 bg-red-500/10 text-center">
          <p className="text-red-400 text-lg font-medium">{error}</p>
        </div>
      )}

      {insight && !loading && (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-8 animate-in fade-in slide-in-from-bottom-8 duration-700">
          <div className="space-y-8 flex flex-col">
            <div className={`p-10 premium-card glow-blue relative overflow-hidden group ${insight.trend === 'Bullish' ? 'border-green-500/30 bg-green-500/5' : insight.trend === 'Bearish' ? 'border-red-500/30 bg-red-500/5' : 'border-blue-500/30 bg-blue-500/5'}`}>
              
              <div className="absolute -right-10 -top-10 opacity-10 group-hover:opacity-20 transition-opacity duration-500">
                <TrendingUp className={`w-64 h-64 ${insight.trend === 'Bullish' ? 'text-green-500' : insight.trend === 'Bearish' ? 'text-red-500' : 'text-blue-500'}`} />
              </div>

              <div className="relative z-10 flex justify-between items-start mb-8">
                <div>
                  <p className="text-muted-foreground text-sm font-bold uppercase tracking-widest">Market Sentiment</p>
                  <h3 className={`text-6xl font-extrabold mt-3 tracking-tighter ${insight.trend === 'Bullish' ? 'text-green-400' : insight.trend === 'Bearish' ? 'text-red-400' : 'text-blue-400'}`}>
                    {insight.trend}
                  </h3>
                </div>
                <div className={`p-4 rounded-2xl ${insight.trend === 'Bullish' ? 'bg-green-500/20 text-green-400' : insight.trend === 'Bearish' ? 'bg-red-500/20 text-red-400' : 'bg-blue-500/20 text-blue-400'}`}>
                  <TrendingUp className="w-8 h-8" />
                </div>
              </div>
              
              <div className="grid grid-cols-2 gap-6 mt-12 relative z-10">
                <div className="bg-background/40 backdrop-blur-md p-6 rounded-3xl border border-white/5 shadow-inner">
                  <p className="text-muted-foreground text-xs font-bold uppercase flex items-center gap-2 tracking-wider"><Shield className="w-4 h-4 text-orange-400" /> Risk Level</p>
                  <p className="text-2xl font-bold mt-2 text-orange-400">{insight.risk}</p>
                </div>
                <div className="bg-background/40 backdrop-blur-md p-6 rounded-3xl border border-white/5 shadow-inner">
                  <p className="text-muted-foreground text-xs font-bold uppercase flex items-center gap-2 tracking-wider"><Clock className="w-4 h-4 text-cyan-400" /> Outlook</p>
                  <p className="text-2xl font-bold mt-2 text-cyan-400">{insight.outlook}</p>
                </div>
              </div>
            </div>

            <div className="p-10 premium-card flex-1">
              <h4 className="font-bold flex items-center gap-3 text-xl text-blue-400 mb-6">
                <Brain className="w-6 h-6" /> AI Reasoning
              </h4>
              <p className="text-muted-foreground leading-relaxed whitespace-pre-line text-base lg:text-lg">
                {insight.explanation}
              </p>
            </div>
          </div>

          <div className="p-10 premium-card flex flex-col justify-center items-center text-center h-full">
            <div className="w-full h-full min-h-[400px] rounded-[2rem] bg-gradient-to-br from-blue-500/10 to-purple-500/5 border border-white/5 flex items-center justify-center p-10 relative overflow-hidden group">
               <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 pointer-events-none mix-blend-overlay"></div>
               <div className="flex flex-col items-center gap-4 relative z-10">
                 <div className="w-16 h-16 bg-blue-500/20 rounded-2xl flex items-center justify-center mb-2 group-hover:scale-110 transition-transform duration-500">
                   <Sparkles className="w-8 h-8 text-blue-400" />
                 </div>
                 <p className="text-2xl font-bold text-white tracking-tight">Visual Analysis Map</p>
                 <p className="text-muted-foreground text-lg">Coming in the next update v2.0</p>
               </div>
            </div>
            <p className="mt-8 text-sm text-muted-foreground max-w-md">
              AI analysis is based on historical patterns and current market data. Performance may vary. <strong className="text-white">This is NOT financial advice.</strong>
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default AIInsights;
