import React, { useState } from 'react';
import { Sparkles, Brain, Shield, Clock, TrendingUp, Search } from 'lucide-react';
import api from '../services/api';

const AIInsights = () => {
  const [search, setSearch] = useState('bitcoin');
  const [insight, setInsight] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchInsight = async () => {
    setLoading(true);
    setError(null);
    try {
      const assetRes = await api.get(`/assets/crypto/${search}`);
      const assetData = JSON.stringify(assetRes.data);
      const brainRes = await api.post('/ai/insight', assetData);
      
      // Basic parsing of the AI result
      const fullText = brainRes.data;
      setInsight({
        trend: fullText.includes('Bullish') ? 'Bullish' : (fullText.includes('Bearish') ? 'Bearish' : 'Neutral'),
        risk: fullText.includes('High') ? 'High' : (fullText.includes('Low') ? 'Low' : 'Moderate'),
        explanation: fullText,
        outlook: '7-14 Days'
      });
    } catch (err) {
      setError('AI Insight Engine currently unavailable. Please check your API keys.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8 pb-12">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-3xl font-bold flex items-center gap-3">
            <Sparkles className="text-primary w-8 h-8" /> AI Insight Engine
          </h2>
          <p className="text-muted mt-1">Deep analysis powered by Mistral 7B LLM.</p>
        </div>
        
        <div className="flex gap-4">
          <div className="relative">
            <input
              type="text"
              placeholder="Asset Symbol (BTC)..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="bg-card border border-border px-10 py-3 rounded-2xl w-64 focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all text-sm"
            />
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted" />
          </div>
          <button 
            onClick={fetchInsight}
            disabled={loading}
            className="bg-primary hover:bg-primary/90 px-6 py-3 rounded-2xl font-bold flex items-center gap-2 transition-all disabled:opacity-50"
          >
            {loading ? 'Analyzing...' : <>Analyze Now <Sparkles className="w-4 h-4" /></>}
          </button>
        </div>
      </div>

      {!insight && !loading && !error && (
        <div className="flex flex-col items-center justify-center p-20 glass rounded-[32px] text-center">
          <div className="w-20 h-20 bg-primary/20 rounded-full flex items-center justify-center mb-6">
            <Brain className="w-10 h-10 text-primary" />
          </div>
          <h3 className="text-xl font-bold">Ready for Analysis</h3>
          <p className="text-muted mt-2 max-w-md mx-auto">
            Input an asset symbol above to get real-time trends, risk levels, and outlooks generated by AI.
          </p>
        </div>
      )}

      {loading && (
        <div className="flex flex-col items-center justify-center p-20 glass rounded-[32px]">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-primary mb-4"></div>
          <p className="text-muted font-medium animate-pulse">Scanning market data and processing insights...</p>
        </div>
      )}

      {error && (
        <div className="p-8 glass rounded-3xl border-red-500/20 bg-red-500/5 text-center">
          <p className="text-red-400 font-medium">{error}</p>
        </div>
      )}

      {insight && !loading && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
          <div className="space-y-6">
            <div className={`p-8 rounded-3xl glass glow ${insight.trend === 'Bullish' ? 'border-green-500/20' : insight.trend === 'Bearish' ? 'border-red-500/20' : 'border-blue-500/20'}`}>
              <div className="flex justify-between items-start mb-6">
                <div>
                  <p className="text-muted text-sm font-semibold uppercase tracking-widest">Market Sentiment</p>
                  <h3 className={`text-4xl font-extrabold mt-2 ${insight.trend === 'Bullish' ? 'text-green-400' : insight.trend === 'Bearish' ? 'text-red-400' : 'text-blue-400'}`}>
                    {insight.trend}
                  </h3>
                </div>
                <TrendingUp className={`w-12 h-12 ${insight.trend === 'Bullish' ? 'text-green-400' : insight.trend === 'Bearish' ? 'text-red-400' : 'text-blue-400'}`} />
              </div>
              
              <div className="grid grid-cols-2 gap-4 mt-8">
                <div className="bg-white/5 p-4 rounded-2xl">
                  <p className="text-muted text-xs font-bold uppercase flex items-center gap-2"><Shield className="w-3 h-3 text-orange-400" /> Risk Level</p>
                  <p className="text-lg font-bold mt-1 text-orange-400">{insight.risk}</p>
                </div>
                <div className="bg-white/5 p-4 rounded-2xl">
                  <p className="text-muted text-xs font-bold uppercase flex items-center gap-2"><Clock className="w-3 h-3 text-cyan-400" /> Outlook</p>
                  <p className="text-lg font-bold mt-1 text-cyan-400">{insight.outlook}</p>
                </div>
              </div>
            </div>

            <div className="p-8 glass rounded-3xl">
              <h4 className="font-bold flex items-center gap-2 text-primary mb-4">AI Reasoning</h4>
              <p className="text-muted leading-relaxed whitespace-pre-line text-sm lg:text-base">
                {insight.explanation}
              </p>
            </div>
          </div>

          <div className="p-8 glass rounded-3xl flex flex-col justify-center items-center text-center">
            <div className="w-full aspect-video rounded-2xl bg-gradient-to-br from-primary/10 to-transparent border border-white/5 flex items-center justify-center p-8">
               <p className="italic text-muted font-medium">Visual AI Market Map coming soon...</p>
            </div>
            <p className="mt-8 text-sm text-muted">
              AI analysis is based on historical patterns and current market data. Performance may vary. This is NOT financial advice.
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default AIInsights;
